default:
	LOG_ANALYZER_FILE=log.txt LOG_ANALYZER_OUTPUT= LOG_ANALYZER_LEVEL=info go run main.go

all:
	LOG_ANALYZER_FILE=./log.txt LOG_ANALYZER_OUTPUT= LOG_ANALYZER_LEVEL=info go run main.go  -file=log2.txt -output=./output.txt -level=warning